version: "3.3"

services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
    restart: unless-stopped
    ports:
      - 80:3000
    volumes:
      - ../:/app
    networks:
      - app
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guiaperguntas
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge